### ISSUE TITLE
I have to add custom security group to pull ecs image.

### ISSUE THREAD

**Issue by zhenghongpeng** [aws-samples/generative-ai-sagemaker-cdk-demo#4]
security_group = ec2.SecurityGroup(
            self, 'FargateSecurityGroup',
            vpc=vpc,
            description='Custom security group for ECS Fargate service',
            allow_all_outbound=False  # Adjust this as per your requirements
        )
        # Add outbound rule for port 443
        security_group.add_egress_rule(
            ec2.Peer.any_ipv4(),
            connection=ec2.Port.tcp(443)
        )
        # Add ingress rule for port 443
        security_group.add_ingress_rule(
            ec2.Peer.any_ipv4(),
            connection=ec2.Port.tcp(443)
        )

Otherwise, it gives ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve ecr registry auth: service call has been retried 3 time(s): RequestError: send request failed caused by: Post "[https://api.ecr.us-west-2.amazonaws.com/ ](https://api.ecr.us-west-2.amazonaws.com/)": dial tcp 34.223.27.76:443: i/o timeout. Please check your task network configuration.

**Comment by Hantzley** [comment]
Some users reported an issue with the container image not being available at deployment. This can be due to a race condition if you are deploying from your local workstation as the container image is built locally and then uploaded to the cloud. 

Can you try deploying the code from a Cloud9 environment? 

I am checking if I can add dependency on the container image before creating the ECS task.
